In [1]:
import pandas as pd

roads = pd.read_csv(r"C:\Users\Admin\Documents\road_safety_dataset_final.csv")

In [2]:
roads

,maxspeed,oneway,length,lanes,police_distance,hospital_distance,restaurant_count,busstop_count,highway_primary,highway_residential,highway_secondary,highway_tertiary,highway_trunk,safety_score
0,40,1,218.972463,1,279.864678,541.398619,0,0,False,False,False,True,False,68
1,40,0,51.986634,1,499.000700,704.077974,0,0,False,False,False,True,False,52
2,40,1,7.459067,4,356.782543,144.099059,1,0,True,False,False,False,False,86
3,40,1,13.380892,1,450.003777,395.560070,0,0,False,False,True,False,False,80
4,40,0,11.192148,1,695.851085,145.483122,1,2,False,True,False,False,False,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,40,0,198.294665,1,806.682269,128.429329,0,0,False,True,False,False,False,79
661,40,0,77.302392,1,601.189458,766.203344,0,0,False,True,False,False,False,67
662,40,0,64.288614,1,533.741902,798.477668,0,0,False,True,False,False,False,63
663,40,0,80.779053,1,725.280477,299.706198,0,0,False,True,False,False,False,79
664,40,1,125.253532,1,699.281579,188.024641,1,1,False,True,False,False,False,90

In [4]:
X = roads.drop(columns=["safety_score"])
y = roads["safety_score"]

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=12,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=12, min_samples_leaf=2, min_samples_split=5,
                      n_estimators=200, random_state=42)

In [7]:
y_pred = rf.predict(X_test)

In [8]:
y_pred

array([64.9269881 , 65.42513294, 54.57061859, 84.48655803, 55.5901847 ,
       49.18151743, 47.13639683, 62.42543561, 81.57150174, 70.39872709,
       76.54078628, 50.24342319, 74.91834122, 33.56087302, 85.24941053,
       49.68895076, 96.97462085, 82.92736251, 98.90215476, 81.87372908,
       55.17762157, 46.439954  , 77.77514032, 46.587317  , 53.85285272,
       63.87080664, 50.13207395, 76.58251803, 47.17151768, 66.19671158,
       78.34661624, 70.33947348, 76.5464705 , 61.83736905, 74.02033462,
       54.49170238, 46.5096984 , 60.50865639, 62.72125992, 63.28422421,
       62.82260128, 64.24214881, 44.93891071, 31.53223683, 45.02491667,
       74.17070186, 73.12075758, 47.781215  , 99.02013294, 62.10739989,
       34.38099405, 96.32196825, 96.91249567, 78.49186075, 95.54804383,
       62.33255285, 56.91890079, 55.42622421, 61.2764219 , 61.93301786,
       78.66444877, 64.29494841, 78.44796068, 77.25050956, 32.95303571,
       84.1525518 , 64.24214881, 48.52225877, 60.42271086, 61.83736905,
       42.97476786, 47.24926983, 80.1692325 , 33.73057107, 86.97734921,
       75.65159906, 41.18127165, 34.71598611, 53.31631313, 82.91062951,
       49.21048828, 86.17414087, 64.73240675, 49.30678409, 60.18302633,
       53.78898575, 94.82221952, 84.30528819, 85.24941053, 60.7552996 ,
       97.56340657, 84.15835137, 72.95136439, 63.63950361, 76.07220511,
       58.40245274, 42.57900072, 47.62893217, 75.61550922, 78.02012316,
       57.1709623 , 70.17266486, 60.65331854, 76.48016695, 83.93325172,
       76.02064809, 98.49464286, 88.77192231, 68.83177309, 76.31920285,
       65.09303481, 98.42976389, 48.49531036, 81.32386363, 70.33947348,
       58.1435066 , 85.81498629, 73.170921  , 57.75809289, 97.90388095,
       61.07471555, 76.51456115, 76.58251803, 96.8438631 , 77.77811703,
       61.03031151, 59.59655495, 83.1211424 , 62.96819968, 48.20679884,
       77.0140474 , 76.77958444, 84.3927004 ])

In [9]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R² Score:", r2_score(y_test, y_pred))

MAE : 4.14747884925966
RMSE: 5.080118678407537
R² Score: 0.9188078356045807

In [10]:
print("Training Score:", rf.score(X_train, y_train))
print("Testing Score :", rf.score(X_test, y_test))

Training Score: 0.97346702632438
Testing Score : 0.9188078356045807

In [11]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance)

                Feature  Importance
9   highway_residential    0.510694
5     hospital_distance    0.291410
4       police_distance    0.147719
8       highway_primary    0.022276
2                length    0.011957
10    highway_secondary    0.005361
6      restaurant_count    0.002854
3                 lanes    0.002568
1                oneway    0.002329
11     highway_tertiary    0.001113
7         busstop_count    0.000980
12        highway_trunk    0.000653
0              maxspeed    0.000086

In [ ]:
roads = roads.drop(columns=[
    "highway_primary_link",
    "highway_secondary_link",
    "highway_trunk_link",
    "junction_roundabout",
    "access_permissive",
    "access_yes",
    "bridge_yes",
    "tunnel_yes",
  
])

In [13]:
roads

,maxspeed,oneway,length,lanes,police_distance,hospital_distance,restaurant_count,busstop_count,highway_primary,highway_residential,highway_secondary,highway_tertiary,highway_trunk,safety_score
0,40,1,218.972463,1,279.864678,541.398619,0,0,False,False,False,True,False,68
1,40,0,51.986634,1,499.000700,704.077974,0,0,False,False,False,True,False,52
2,40,1,7.459067,4,356.782543,144.099059,1,0,True,False,False,False,False,86
3,40,1,13.380892,1,450.003777,395.560070,0,0,False,False,True,False,False,80
4,40,0,11.192148,1,695.851085,145.483122,1,2,False,True,False,False,False,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,40,0,198.294665,1,806.682269,128.429329,0,0,False,True,False,False,False,79
661,40,0,77.302392,1,601.189458,766.203344,0,0,False,True,False,False,False,67
662,40,0,64.288614,1,533.741902,798.477668,0,0,False,True,False,False,False,63
663,40,0,80.779053,1,725.280477,299.706198,0,0,False,True,False,False,False,79
664,40,1,125.253532,1,699.281579,188.024641,1,1,False,True,False,False,False,90

In [14]:
X = roads.drop(columns=["safety_score"])
y = roads["safety_score"]

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    min_samples_split=8,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, max_features='sqrt', min_samples_leaf=4,
                      min_samples_split=8, n_estimators=300, random_state=42)

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = rf.predict(X_test)

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R² Score:", r2_score(y_test, y_pred))

print("Training Score:", rf.score(X_train, y_train))
print("Testing Score :", rf.score(X_test, y_test))

MAE : 4.7157427594340495
RMSE: 5.844570518460506
R² Score: 0.8925338702263041
Training Score: 0.9323394775839728
Testing Score : 0.8925338702263041

In [18]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [5, 10, 15, 20, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2", None]
}

search = RandomizedSearchCV(
    RandomForestRegressor(random_state=42),
    param_grid,
    n_iter=20,
    cv=5,
    scoring="r2",
    random_state=42
)

search.fit(X_train, y_train)

print(search.best_params_)

{'n_estimators': 300, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': None, 'max_depth': 20}

In [19]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    rf,
    X,
    y,
    cv=5,
    scoring="r2"
)

print(scores)
print(scores.mean())

[0.88457222 0.92249952 0.83680349 0.79528399 0.9200368 ]
0.8718392037020102

In [20]:
best_rf = search.best_estimator_

best_rf.fit(X_train, y_train)

y_pred = best_rf.predict(X_test)

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R² :", r2_score(y_test, y_pred))

print("Training :", best_rf.score(X_train, y_train))
print("Testing  :", best_rf.score(X_test, y_test))

MAE : 4.150711109838665
RMSE: 5.089814381162775
R² : 0.9184976198931497
Training : 0.9666290893733286
Testing  : 0.9184976198931497

In [22]:
import joblib

joblib.dump(best_rf, "road_safety_model.pkl")

['road_safety_model.pkl']

In [23]:
feature_names = X.columns.tolist()

joblib.dump(feature_names, "feature_names.pkl")

['feature_names.pkl']

In [24]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB 187.9 kB/s eta 0:09:02
   ---------------------------------------- 0.1/101.7 MB 328.6 kB/s eta 0:05:10
   ---------------------------------------- 0.1/101.7 MB 328.6 kB/s eta 0:05:10
   ---------------------------------------- 0.1/101.7 MB 473.7 kB/s eta 0:03:35
   ---------------------------------------- 0.2/101.7 MB 626.9 kB/s eta 0:02:42
   ---------------------------------------- 0.3/101.7 MB 787.7 kB/s eta 0:02:09
   ---------------------------------------- 0.5/101.7 MB 1.1 MB/s eta 0:01:36
   ---------------------------------------- 0.6/101.7 MB 1.3 MB/s eta 0:01:19
   ---------------------------------------- 0.9/101.7 MB 1.7 MB/s eta 0:01:00
   ---------------------------------------- 1.1/101.7 MB 1.9 MB/s eta 0:00:53
    --------------------------------------- 1.4/101.7 MB 2.3 MB/s eta 0:00:43
    --------------------------------------- 1.7/101.7 MB 2.5 MB/s eta 0:00:40
    --------------------------------------- 1.9/101.7 MB 2.8 MB/s eta 0:00:37
    --------------------------------------- 2.2/101.7 MB 3.0 MB/s eta 0:00:34
    --------------------------------------- 2.4/101.7 MB 3.0 MB/s eta 0:00:33
   - -------------------------------------- 2.5/101.7 MB 3.0 MB/s eta 0:00:34
   - -------------------------------------- 2.9/101.7 MB 3.2 MB/s eta 0:00:31
   - -------------------------------------- 3.1/101.7 MB 3.3 MB/s eta 0:00:30
   - -------------------------------------- 3.4/101.7 MB 3.4 MB/s eta 0:00:29
   - -------------------------------------- 3.6/101.7 MB 3.5 MB/s eta 0:00:29
   - -------------------------------------- 3.7/101.7 MB 3.5 MB/s eta 0:00:29
   - -------------------------------------- 4.0/101.7 MB 3.6 MB/s eta 0:00:28
   - -------------------------------------- 4.1/101.7 MB 3.5 MB/s eta 0:00:28
   - -------------------------------------- 4.2/101.7 MB 3.4 MB/s eta 0:00:29
   - -------------------------------------- 4.4/101.7 MB 3.4 MB/s eta 0:00:29
   - -------------------------------------- 4.5/101.7 MB 3.4 MB/s eta 0:00:29
   - -------------------------------------- 4.7/101.7 MB 3.5 MB/s eta 0:00:29
   - -------------------------------------- 4.9/101.7 MB 3.5 MB/s eta 0:00:28
   -- ------------------------------------- 5.1/101.7 MB 3.5 MB/s eta 0:00:28
   -- ------------------------------------- 5.4/101.7 MB 3.5 MB/s eta 0:00:28
   -- ------------------------------------- 5.6/101.7 MB 3.6 MB/s eta 0:00:28
   -- ------------------------------------- 5.8/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.0/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.1/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.3/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.5/101.7 MB 3.7 MB/s eta 0:00:27
   -- ------------------------------------- 6.6/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.7/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.8/101.7 MB 3.5 MB/s eta 0:00:27
   -- ------------------------------------- 7.0/101.7 MB 3.5 MB/s eta 0:00:27
   -- ------------------------------------- 7.2/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 7.3/101.7 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 7.5/101.7 MB 3.5 MB/s eta 0:00:27
   --- ------------------------------------ 7.7/101.7 MB 3.6 MB/s eta 0:00:27
   --- ------------------------------------ 7.9/101.7 MB 3.6 MB/s eta 0:00:27
   --- ------------------------------------ 8.1/101.7 MB 3.6 MB/s eta 0:00:27
   --- ------------------------------------ 8.3/101.7 MB 3.6 MB/s eta 0:00:27
   --- ------------------------------------ 8.4/101.7 MB 3.6 MB/s eta 0:00:27
   --- ------------------------------------ 8.6/101.7 MB 3.6 MB/s eta 0:00:27
   --- ------------------------------------ 8.7/101.7 MB 3.6 MB/s eta 0:00:27
   --- ------------------------------------ 8.9/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 9.1/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 9.2/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 9.4/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 9.6/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 9.9/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 10.0/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 10.1/101.7 MB 3.6 MB/s eta 0:00:26
   --- ------------------------------------ 10.1/101.7 MB 3.5 MB/s eta 0:00:26
   ---- ----------------------------------- 10.2/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 10.2/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 10.3/101.7 MB 3.6 MB/s eta 0:00:26
   ---- ----------------------------------- 10.4/101.7 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 10.4/101.7 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 10.5/101.7 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 10.6/101.7 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 10.7/101.7 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 10.8/101.7 MB 3.6 MB/s eta 0:00:25
   ---- ----------------------------------- 10.9/101.7 MB 3.6 MB/s eta 0:00:26
   ---- ----------------------------------- 10.9/101.7 MB 3.6 MB/s eta 0:00:26
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:26
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.1/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 11.2/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 11.3/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 11.4/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 11.6/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 11.6/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 11.7/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 11.9/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 12.0/101.7 MB 3.2 MB/s eta 0:00:29
   ---- ----------------------------------- 12.1/101.7 MB 3.2 MB/s eta 0:00:29
   ---- ----------------------------------- 12.2/101.7 MB 3.1 MB/s eta 0:00:29
   ---- ----------------------------------- 12.3/101.7 MB 3.1 MB/s eta 0:00:29
   ---- ----------------------------------- 12.3/101.7 MB 3.1 MB/s eta 0:00:30
   ---- ----------------------------------- 12.4/101.7 MB 3.0 MB/s eta 0:00:30
   ---- ----------------------------------- 12.4/101.7 MB 3.0 MB/s eta 0:00:30
   ---- ----------------------------------- 12.5/101.7 MB 3.0 MB/s eta 0:00:30
   ---- ----------------------------------- 12.6/101.7 MB 2.9 MB/s eta 0:00:31
   ---- ----------------------------------- 12.6/101.7 MB 2.9 MB/s eta 0:00:31
   ---- ----------------------------------- 12.6/101.7 MB 2.9 MB/s eta 0:00:31
   ---- ----------------------------------- 12.6/101.7 MB 2.9 MB/s eta 0:00:32
   ---- ----------------------------------- 12.7/101.7 MB 2.8 MB/s eta 0:00:32
   ---- ----------------------------------- 12.7/101.7 MB 2.8 MB/s eta 0:00:32
   ----- ---------------------------------- 12.9/101.7 MB 2.8 MB/s eta 0:00:32
   ----- ---------------------------------- 13.0/101.7 MB 2.8 MB/s eta 0:00:32
   ----- ---------------------------------- 13.1/101.7 MB 2.8 MB/s eta 0:00:33
   ----- ---------------------------------- 13.2/101.7 MB 2.7 MB/s eta 0:00:33
   ----- ---------------------------------- 13.3/101.7 MB 2.7 MB/s eta 0:00:33
   ----- ---------------------------------- 13.3/101.7 MB 2.7 MB/s eta 0:00:34
   ----- ---------------------------------- 13.5/101.7 MB 2.7 MB/s eta 0:00:34
   ----- ---------------------------------- 13.5/101.7 MB 2.6 MB/s eta 0:00:34
   ----- ---------------------------------- 13.7/101.7 MB 2.6 MB/s eta 0:00:34
   ----- ---------------------------------- 13.7/101.7 MB 2.6 MB/s eta 0:00:34
   ----- ---------------------------------- 13.8/101.7 MB 2.6 MB/s eta 0:00:34
   ----- ---------------------------------- 14.0/101.7 MB 2.6 MB/s eta 0:00:34
   ----- ---------------------------------- 14.1/101.7 MB 2.6 MB/s eta 0:00:35
   ----- ---------------------------------- 14.2/101.7 MB 2.6 MB/s eta 0:00:35
   ----- ---------------------------------- 14.3/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 14.3/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 14.4/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 14.5/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 14.7/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 14.8/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 14.9/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 15.1/101.7 MB 2.5 MB/s eta 0:00:35
   ----- ---------------------------------- 15.2/101.7 MB 2.5 MB/s eta 0:00:35
   ------ --------------------------------- 15.4/101.7 MB 2.5 MB/s eta 0:00:35
   ------ --------------------------------- 15.5/101.7 MB 2.5 MB/s eta 0:00:36
   ------ --------------------------------- 15.6/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 15.7/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 15.8/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.0/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.0/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.2/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.3/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.5/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.6/101.7 MB 2.4 MB/s eta 0:00:37
   ------ --------------------------------- 16.7/101.7 MB 2.4 MB/s eta 0:00:37
   ------ --------------------------------- 16.8/101.7 MB 2.4 MB/s eta 0:00:37
   ------ --------------------------------- 16.9/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 17.1/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 17.2/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 17.3/101.7 MB 2.3 MB/s eta 0:00:36
   ------ --------------------------------- 17.4/101.7 MB 2.3 MB/s eta 0:00:36
   ------ --------------------------------- 17.6/101.7 MB 2.3 MB/s eta 0:00:36
   ------ --------------------------------- 17.7/101.7 MB 2.3 MB/s eta 0:00:36
   ------- -------------------------------- 17.8/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.0/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.1/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.2/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.3/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.4/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.6/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.7/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 18.8/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 19.0/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 19.1/101.7 MB 2.2 MB/s eta 0:00:37
   ------- -------------------------------- 19.3/101.7 MB 2.2 MB/s eta 0:00:37
   ------- -------------------------------- 19.4/101.7 MB 2.2 MB/s eta 0:00:37
   ------- -------------------------------- 19.5/101.7 MB 2.2 MB/s eta 0:00:37
   ------- -------------------------------- 19.6/101.7 MB 2.2 MB/s eta 0:00:37
   ------- -------------------------------- 19.7/101.7 MB 2.2 MB/s eta 0:00:37
   ------- -------------------------------- 19.8/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 19.9/101.7 MB 2.2 MB/s eta 0:00:37
   ------- -------------------------------- 20.1/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 20.2/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 20.3/101.7 MB 2.2 MB/s eta 0:00:38
   -------- ------------------------------- 20.5/101.7 MB 2.2 MB/s eta 0:00:37
   -------- ------------------------------- 20.6/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 20.8/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 20.9/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 21.0/101.7 MB 2.3 MB/s eta 0:00:35
   -------- ------------------------------- 21.1/101.7 MB 2.3 MB/s eta 0:00:35
   -------- ------------------------------- 21.3/101.7 MB 2.4 MB/s eta 0:00:34
   -------- ------------------------------- 21.4/101.7 MB 2.4 MB/s eta 0:00:34
   -------- ------------------------------- 21.6/101.7 MB 2.4 MB/s eta 0:00:34
   -------- ------------------------------- 21.8/101.7 MB 2.4 MB/s eta 0:00:34
   -------- ------------------------------- 21.9/101.7 MB 2.4 MB/s eta 0:00:33
   -------- ------------------------------- 22.1/101.7 MB 2.4 MB/s eta 0:00:33
   -------- ------------------------------- 22.2/101.7 MB 2.4 MB/s eta 0:00:33
   -------- ------------------------------- 22.3/101.7 MB 2.4 MB/s eta 0:00:33
   -------- ------------------------------- 22.5/101.7 MB 2.4 MB/s eta 0:00:33
   -------- ------------------------------- 22.6/101.7 MB 2.5 MB/s eta 0:00:33
   -------- ------------------------------- 22.8/101.7 MB 2.5 MB/s eta 0:00:32
   --------- ------------------------------ 22.9/101.7 MB 2.7 MB/s eta 0:00:30
   --------- ------------------------------ 23.1/101.7 MB 2.7 MB/s eta 0:00:30
   --------- ------------------------------ 23.2/101.7 MB 2.7 MB/s eta 0:00:30
   --------- ------------------------------ 23.3/101.7 MB 2.7 MB/s eta 0:00:30
   --------- ------------------------------ 23.5/101.7 MB 2.7 MB/s eta 0:00:29
   --------- ------------------------------ 23.7/101.7 MB 2.7 MB/s eta 0:00:29
   --------- ------------------------------ 23.8/101.7 MB 2.8 MB/s eta 0:00:29
   --------- ------------------------------ 24.0/101.7 MB 2.8 MB/s eta 0:00:29
   --------- ------------------------------ 24.1/101.7 MB 2.8 MB/s eta 0:00:28
   --------- ------------------------------ 24.2/101.7 MB 2.8 MB/s eta 0:00:28
   --------- ------------------------------ 24.5/101.7 MB 2.8 MB/s eta 0:00:28
   --------- ------------------------------ 24.6/101.7 MB 2.9 MB/s eta 0:00:27
   --------- ------------------------------ 24.8/101.7 MB 2.9 MB/s eta 0:00:27
   --------- ------------------------------ 24.9/101.7 MB 2.9 MB/s eta 0:00:27
   --------- ------------------------------ 25.1/101.7 MB 2.9 MB/s eta 0:00:27
   --------- ------------------------------ 25.2/101.7 MB 2.9 MB/s eta 0:00:27
   --------- ------------------------------ 25.2/101.7 MB 2.9 MB/s eta 0:00:27
   --------- ------------------------------ 25.4/101.7 MB 2.9 MB/s eta 0:00:27
   ---------- ----------------------------- 25.5/101.7 MB 2.8 MB/s eta 0:00:27
   ---------- ----------------------------- 25.6/101.7 MB 2.8 MB/s eta 0:00:27
   ---------- ----------------------------- 25.7/101.7 MB 2.8 MB/s eta 0:00:27
   ---------- ----------------------------- 25.9/101.7 MB 2.9 MB/s eta 0:00:27
   ---------- ----------------------------- 26.0/101.7 MB 2.9 MB/s eta 0:00:27
   ---------- ----------------------------- 26.1/101.7 MB 2.9 MB/s eta 0:00:27
   ---------- ----------------------------- 26.2/101.7 MB 2.9 MB/s eta 0:00:27
   ---------- ----------------------------- 26.3/101.7 MB 2.8 MB/s eta 0:00:27
   ---------- ----------------------------- 26.5/101.7 MB 2.9 MB/s eta 0:00:27
   ---------- ----------------------------- 26.7/101.7 MB 2.9 MB/s eta 0:00:27
   ---------- ----------------------------- 26.9/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.0/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.1/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.2/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.3/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.4/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.6/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.7/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.7/101.7 MB 2.9 MB/s eta 0:00:26
   ---------- ----------------------------- 27.8/101.7 MB 2.8 MB/s eta 0:00:27
   ---------- ----------------------------- 27.8/101.7 MB 2.8 MB/s eta 0:00:27
   ---------- ----------------------------- 27.9/101.7 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 28.0/101.7 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 28.1/101.7 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 28.2/101.7 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 28.3/101.7 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 28.4/101.7 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 28.5/101.7 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 28.6/101.7 MB 2.7 MB/s eta 0:00:27
   ----------- ---------------------------- 28.7/101.7 MB 2.7 MB/s eta 0:00:27
   ----------- ---------------------------- 28.7/101.7 MB 2.7 MB/s eta 0:00:28
   ----------- ---------------------------- 28.8/101.7 MB 2.7 MB/s eta 0:00:28
   ----------- ---------------------------- 28.9/101.7 MB 2.7 MB/s eta 0:00:28
   ----------- ---------------------------- 29.0/101.7 MB 2.7 MB/s eta 0:00:28
   ----------- ---------------------------- 29.0/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 29.1/101.7 MB 2.7 MB/s eta 0:00:28
   ----------- ---------------------------- 29.2/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 29.4/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 29.5/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 29.6/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 29.7/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 29.8/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 30.0/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 30.1/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 30.2/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 30.3/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 30.4/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 30.5/101.7 MB 2.6 MB/s eta 0:00:28
   ------------ --------------------------- 30.5/101.7 MB 2.6 MB/s eta 0:00:28
   ------------ --------------------------- 30.7/101.7 MB 2.6 MB/s eta 0:00:28

[notice] A new release of pip is available: 24.0 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from xgboost import XGBRegressor

In [26]:
xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [27]:
y_pred = xgb.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R² :", r2_score(y_test, y_pred))

print("Training :", xgb.score(X_train, y_train))
print("Testing  :", xgb.score(X_test, y_test))

MAE : 4.416049480438232
RMSE: 5.407020822599575
R² : 0.9080222845077515
Training : 0.9844669103622437
Testing  : 0.9080222845077515

In [29]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    xgb,
    X,
    y,
    cv=5,
    scoring="r2"
)

print(scores)
print("Average CV Score:", scores.mean())

[0.88829583 0.95061982 0.85166246 0.83086371 0.9147718 ]
Average CV Score: 0.8872427225112915

In [30]:
from sklearn.model_selection import RandomizedSearchCV

params = {
    "n_estimators": [200, 300, 500],
    "max_depth": [3, 4, 5, 6, 8],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0],
    "min_child_weight": [1, 3, 5],
    "gamma": [0, 0.1, 0.2, 0.3]
}

search = RandomizedSearchCV(
    estimator=XGBRegressor(
        objective="reg:squarederror",
        random_state=42
    ),
    param_distributions=params,
    n_iter=20,
    cv=5,
    scoring="r2",
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print(search.best_params_)
print(search.best_score_)

{'subsample': 0.7, 'n_estimators': 300, 'min_child_weight': 5, 'max_depth': 3, 'learning_rate': 0.05, 'gamma': 0.3, 'colsample_bytree': 1.0}
0.925249433517456

In [31]:
best_xgb = search.best_estimator_

best_xgb.fit(X_train, y_train)

y_pred = best_xgb.predict(X_test)

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R² :", r2_score(y_test, y_pred))

print("Training :", best_xgb.score(X_train, y_train))
print("Testing  :", best_xgb.score(X_test, y_test))

MAE : 4.010239124298096
RMSE: 4.9450980527161
R² : 0.9230663776397705
Training : 0.9666467905044556
Testing  : 0.9230663776397705

In [32]:
joblib.dump(best_xgb, "road_safety_xgboost.pkl")

['road_safety_xgboost.pkl']

In [33]:
joblib.dump(X.columns.tolist(), "feature_names.pkl")

['feature_names.pkl']

In [34]:
import joblib

model = joblib.load("road_safety_xgboost.pkl")

In [35]:
feature_names = joblib.load("feature_names.pkl")
print(feature_names)

['maxspeed', 'oneway', 'length', 'lanes', 'police_distance', 'hospital_distance', 'restaurant_count', 'busstop_count', 'highway_primary', 'highway_residential', 'highway_secondary', 'highway_tertiary', 'highway_trunk']

In [36]:
import pandas as pd

new_route = pd.DataFrame([{
    "maxspeed": 40,
    "oneway": 1,
    "length": 250,
    "lanes": 2,
    "police_distance": 300,
    "hospital_distance": 500,
    "restaurant_count": 2,
    "busstop_count": 1,
    "highway_primary": False,
    "highway_residential": True,
    "highway_secondary": False,
    "highway_tertiary": False,
    "highway_trunk": False
}])

In [37]:
prediction = model.predict(new_route)

print("Predicted Safety Score:", prediction[0])

Predicted Safety Score: 91.21003